name: VillagerOptimiser
main: com.froobworld.avl.Avl
authors: [froobynooby, twinklestar03, RENaa_FD]
version: 1.3
api-version: 1.14
description: >
             Limits frequency of expensive pathfinding operations of villagers.
